# Modelo Insumo-Producto con Numpy

Existe  un modelo de economía que es usado con frecuencia es el Modelo de Insumo-Producto de Leontieff, que tiene como objetivo medir el nivel de productividad de múltiples industrias ante la demanda. Esta es una herramienta para analizar los cambios de la productividad ante una nueva demanda. 


Numpy es una librería de Python que nos ayuda a trabajar con algebra Lineal, dado que este modelo se fundamenta en el uso de Matrices.

## Ejemplo 1

Supongamos en un sistema económico que tiene n industrias. Existen dos tipos de demandas en
cada industria: la primera, una demanda externa desde afuera del sistema. Por ejemplo, si
el sistema es un país, la demanda externa puede provenir de otro país. Segunda, la demanda que hace una industria a otra industria en el mismo sistema. Por ejemplo, en Perú la industria textil demanda parte de la producción de la industria del algodón.

Para este ejemplo, la producción de textil destinada a la industria textil es 60 mil, para la misma industria es 64 mil y para la demanda externa es 70. La producción de algodón destinada a la industria textil es 100 mil, para la misma industria 48 mil y para la la demanda externa es 60 mil. Ahora se ha estimado en 3 años que la demanda externa se reducira en 70 para la industria textil y 60 para la industria de algodón ¿Cuál sera la nueva producción?

In [1]:
import numpy as np

In [2]:
demanda_externa_a = np.array([70,60])
Matrix_prod1 = ([60,64],[100,48])
ProdTotal = np.array([200,160]) 


In [3]:
inv1 = np.linalg.inv(np.identity(2)*ProdTotal)
inv1

array([[0.005  , 0.     ],
       [0.     , 0.00625]])

In [5]:
matrix_1 = np.matmul(Matrix_prod1,inv1)
matrix_1

array([[0.3, 0.4],
       [0.5, 0.3]])

In [6]:
matrix_2 = np.linalg.inv(np.identity(2)-matrix_1)
Matrix_prod = np.matmul(matrix_2,demanda_externa_a)
Matrix_prod

array([251.72413793, 265.51724138])

La industria textil debe producir 251.7 mil y la industria de algodón 265 mil de su producto con el fin de cumplir con las demandas finales de la proyección
 a 3 años

## Ejemplo 2

Supongamos que existen 3 industrias, la de agricultura, manufactura, servicios, existe una demanda externa de 80 mil, 140 mil y para 200 mil respectivamente. Hallar la producción total si la Agricultura para si misma produce un 40 %, para la  manufactura un 3 % , un 2 % para la de servicios. La industria manufacturera produce para la agricultura produce un 6%, para si misma un 37% y para el de servicios un 10 %. La industria de servicios produce para la agricultura un 12 %, para la manufactura un 15% y para si misma un 19%. 

In [7]:
prod2 = ([.4,.03,.02], [.06,.37, .1], [.12,.15,.19])
demanda_externa_b = np.array = (80 ,140, 200)

In [8]:
matrix_leon2 = np.linalg.inv(np.identity(3)-prod2)
matrix_leon3 = np.matmul(matrix_leon2, demanda_externa_b)
matrix_leon3

array([158.56573705, 288.73225049, 323.87373583])

## Ejemplo 3

Supongamos que existen 3 industrias, la de energia, construcción, transporte, existe una demanda externa de 100 mil, 50 mil y para 100 mil respectivamente. Hallar la producción total si la Industria de Energia para si misma produce un 40 %, para la  Construcción un 20 % , un 10 % para la de transporte. La industria de Construccion para la agriultura produce un 20%, para si misma un 40% y para el de transporte un 10 %. En la industria de Tranporte, se produce para la Industria Energetica un  15%, para la manufactura un 20% y para si misma un 20%. 

In [9]:
prod3 = ([.4,.2,.1],[.2,.4,.1],[.15,.2,.2])
demanda_externa_c = [100 , 50 , 100]

In [10]:
matrix_3 = np.linalg.inv(np.identity(3)-prod3)
matrix_leon4 = np.matmul(matrix_3,demanda_externa_c)
matrix_leon4

array([276.31578947, 213.81578947, 230.26315789])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c52f5e7d-67d9-4515-996d-7bdbe2c5d3cd' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>